### ISSUE TITLE
Tunnel L2 protocols with Q-in-Q

### ISSUE THREAD

**Issue by graboskyc** [QualiSystems/cloudshell-networking-cisco#66]
Build a connection between two resources with an L2 switch in the middle. 

|DUT1| ---- |TOR| ---- |DUT2|

We push the default config when the attribute is QinQ==true, the config looks like this:
![capture](https://user-images.githubusercontent.com/1686038/28478168-3257e23a-6e25-11e7-95d6-42ef11c10cfc.PNG)

It should have this extra config line:
`l2protocol tunnel`

This will tunnel L2 protocols like CDP so the middle switch is fully transparent.

**Comment by GalcQuali** [comment]
This is by design - not all customers wants to allow all or some L2 protocols in the tunnel. .
In case the customer do want, this can be done by customizing the shell

You can raise in the idea box the option to have this as a check box (or something similar) in the connectivity service and the shell will execute the command accordingly.
